/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An atvise display configuration file
 */
export interface Display {
  /**
   * A display's title
   */
  title?: string;
  /**
   * A short description of the display
   */
  description?: string;
  /**
   * Display parameters
   */
  parameters?: {
    name: string;
    desc?: string;
    valuetype:
      | 'address'
      | 'display'
      | 'string'
      | 'trstring'
      | 'number'
      | 'bool'
      | 'color'
      | 'enum'
      | 'global';
    behavior: 'mandatory' | 'optional';
    defaultvalue?: string;
    config?: string;
    [k: string]: unknown;
  }[];
  /**
   * External scripts to load
   */
  dependencies?: string[];
  [k: string]: unknown;
}
