/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An atvise display configuration file
 */
export interface DisplayConfig {
  /**
   * A display's title
   */
  title?: string;
  /**
   * A short description of the display
   */
  description?: string;
  /**
   * Display parameters
   */
  parameters?: {
    /**
     * The parameter's name
     */
    name: string;
    /**
     * A short description of what the parameter does
     */
    desc?: string;
    /**
     * A string to search in the code and replace with the parameter's value
     */
    substitute?: string;
    /**
     * The parameter's type
     */
    valuetype:
      | 'address'
      | 'display'
      | 'string'
      | 'trstring'
      | 'number'
      | 'bool'
      | 'color'
      | 'enum'
      | 'global';
    behavior: 'mandatory' | 'optional' | 'hidden';
    defaultvalue?: string;
    /**
     * Holds possible values in enum parameters
     */
    config?: string;
    group?: string;
    target?: {
      namespaceIndex: number;
      name: string;
    };
    [k: string]: unknown;
  }[];
  /**
   * External scripts to load
   */
  dependencies?: string[];
  [k: string]: unknown;
}
